language: objective-c
script: ./script/cibuild
env:
  - HH_TRAVIS_TEST=1
  - HH_TRAVIS_TEST=2
  - HH_TRAVIS_TEST=3
  - HH_TRAVIS_TEST=4
  - HH_TRAVIS_TEST=5
  - HH_TRAVIS_TEST=6
  - HH_TRAVIS_TEST=7
  - HH_TRAVIS_TEST=8
  - HH_TRAVIS_TEST=9
  - HH_TRAVIS_TEST=10
  - HH_TRAVIS_TEST=11
  - HH_TRAVIS_TEST=12
  - HH_TRAVIS_TEST=13
  - HH_TRAVIS_TEST=14
  - HH_TRAVIS_TEST=15
  - HH_TRAVIS_TEST=16
  - HH_TRAVIS_TEST=17
  - HH_TRAVIS_TEST=18
  - HH_TRAVIS_TEST=19
  - HH_TRAVIS_TEST=20
